<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>..\..\images\mila.ico</ApplicationIcon>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <AssemblyName>MilaController</AssemblyName>
    <RootNamespace>Mila</RootNamespace>
  </PropertyGroup>

</Project>
